# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_cluster_matrix <- function(distribution, threshold, side) {
    .Call('_permuco_get_cluster_matrix', PACKAGE = 'permuco', distribution, threshold, side)
}

get_clusterdepth_head <- function(cluster, border) {
    .Call('_permuco_get_clusterdepth_head', PACKAGE = 'permuco', cluster, border)
}

get_clusterdepth_tail <- function(cluster, border) {
    .Call('_permuco_get_clusterdepth_tail', PACKAGE = 'permuco', cluster, border)
}

depth_distribution_head <- function(distribution, head) {
    .Call('_permuco_depth_distribution_head', PACKAGE = 'permuco', distribution, head)
}

depth_distribution_tail <- function(distribution, tail) {
    .Call('_permuco_depth_distribution_tail', PACKAGE = 'permuco', distribution, tail)
}

depth_distribution_unique <- function(distribution, head, tail) {
    .Call('_permuco_depth_distribution_unique', PACKAGE = 'permuco', distribution, head, tail)
}

vector_extend <- function(x, threshold) {
    .Call('_permuco_vector_extend', PACKAGE = 'permuco', x, threshold)
}

tfce_distribution <- function(distribution, E, H, dh, dhi) {
    .Call('_permuco_tfce_distribution', PACKAGE = 'permuco', distribution, E, H, dh, dhi)
}

