# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_cluster_matrix <- function(distribution, threshold) {
    .Call('_permuco_get_cluster_matrix', PACKAGE = 'permuco', distribution, threshold)
}

